# Number guessing game
# Random number will be generated by function based on user input range
# User needs to guess that random number


import random

def get_num(bound):

    while True:
        try:
            num = int(input(f"Enter {bound}: "))
            return num
            False
        except ValueError:
            print("Please input valid number.")

print("\nNumber Guessing Game")
min_range = get_num("Lower Range")
max_range = get_num("Upper Range")   


# Generate random number on given range using Random.randint() function
x = random.randint(min_range, max_range)

count = 0
# iterate User's guess number until it is matched with Random number
while True:
    
    user_guess = int(input("Enter your guess: "))

    if x == user_guess:
        count = count + 1
        print(f"Congrat! It's match in {count} guess.\n")
        break
    elif x > user_guess:
        count += 1
        print(f"Your guess is too low. Your guess is {count} time.")        
    elif x < user_guess:
        count += 1
        print(f"Your guess is too high. Your guess is {count} time.")